apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: udacity
  name: techtrends
  namespace: sandbox
spec:
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
  selector:
    app: techtrends
    tag: udacity
  type: ClusterIP
